---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-hetzner:domain-solver
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
rules:
  - apiGroups:
      - acme.ftsell.de
    resources:
      - '*'
    verbs:
      - 'create'
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-hetzner:flowcontrol-solver
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
rules:
  - apiGroups:
      - "flowcontrol.apiserver.k8s.io"
    resources:
      - 'prioritylevelconfigurations'
      - 'flowschemas'
    verbs:
      - 'list'
      - 'watch'
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-hetzner:auth-delegator
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-hetzner
    namespace: cert-manager
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-hetzner:domain-solver
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-hetzner:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-hetzner:flowcontrol-solver
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-hetzner:flowcontrol-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-hetzner
    namespace: "cert-manager"
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-hetzner:secret-reader
  namespace: cert-manager
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    resourceNames:
        - hetzner-secret
    verbs:
      - "get"
      - "watch"
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-hetzner:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-hetzner
    namespace: cert-manager
---
# Source: cert-manager-webhook-hetzner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-hetzner:secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-hetzner:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-hetzner
    namespace: cert-manager
---
# Source: cert-manager-webhook-hetzner/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: cert-manager-webhook-hetzner
    release: cert-manager-webhook-hetzner
---
# Source: cert-manager-webhook-hetzner/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      app: cert-manager-webhook-hetzner
      release: cert-manager-webhook-hetzner
  template:
    metadata:
      labels:
        app: cert-manager-webhook-hetzner
        release: cert-manager-webhook-hetzner
    spec:
      serviceAccountName: cert-manager-webhook-hetzner
      containers:
        - name: cert-manager-webhook-hetzner
          image: "ghcr.io/vadimkim/cert-manager-webhook-hetzner:1.3.0"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
            - --secure-port=8443
          env:
            - name: GROUP_NAME
              value: "acme.ftsell.de"
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
      volumes:
        - name: certs
          secret:
            secretName: cert-manager-webhook-hetzner-webhook-tls
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
---
# Source: cert-manager-webhook-hetzner/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.ftsell.de
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/cert-manager-webhook-hetzner-webhook-tls"
spec:
  group: acme.ftsell.de
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-hetzner
    namespace: cert-manager
  version: v1alpha1
---
# Source: cert-manager-webhook-hetzner/templates/pki.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-hetzner-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
spec:
  secretName: cert-manager-webhook-hetzner-ca
  duration: 43800h0m0s # 5y
  issuerRef:
    name: cert-manager-webhook-hetzner-selfsign
  commonName: "ca.cert-manager-webhook-hetzner.cert-manager"
  isCA: true
---
# Source: cert-manager-webhook-hetzner/templates/pki.yaml
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-hetzner-webhook-tls
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
spec:
  secretName: cert-manager-webhook-hetzner-webhook-tls
  duration: 8760h0m0s # 1y
  issuerRef:
    name: cert-manager-webhook-hetzner-ca
  dnsNames:
    - cert-manager-webhook-hetzner
    - cert-manager-webhook-hetzner.cert-manager
    - cert-manager-webhook-hetzner.cert-manager.svc
---
# Source: cert-manager-webhook-hetzner/templates/pki.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-hetzner-selfsign
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
spec:
  selfSigned: {}
---
# Source: cert-manager-webhook-hetzner/templates/pki.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-hetzner-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-hetzner
    chart: cert-manager-webhook-hetzner-1.3.1
    release: cert-manager-webhook-hetzner
    heritage: Helm
spec:
  ca:
    secretName: cert-manager-webhook-hetzner-ca
