apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
commonLabels:
  app.kubernetes.io/part-of: keycloak

resources:
  - manifests/namespace.yml
  - manifests/keycloak-deployment.yml
  - manifests/keycloak-service.yml
  - manifests/ingress.yml

images:
  - name: quay.io/keycloak/keycloak
    newTag: "25.0"

configMapGenerator:
  - name: keycloak
    envs:
      - config/keycloak.env

secretGenerator:
  - name: keycloak
    envs:
      - config/keycloak.secret.env
