apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
commonLabels:
  app.kubernetes.io/part-of: forgejo

resources:
  - manifests/deployment.yml
  - manifests/storage.yml
  - manifests/service.yml
  - manifests/namespace.yml
  - manifests/ingress.yml

images:
  - name: codeberg.org/forgejo/forgejo
    newTag: "7"

configMapGenerator:
  - name: forgejo
    envs:
      - config.env

secretGenerator:
  - name: forgejo
    envs:
      - config.secret.env
