apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox
commonLabels:
  app.kubernetes.io/part-of: netbox

resources:
  - manifests/namespace.yml
  - manifests/redis-cache.yml
  - manifests/redis-db.yml
  - manifests/netbox.yml
  - manifests/ingress.yml

images:
  - name: docker.io/redis
    newTag: "7-alpine"
  - name: docker.io/netboxcommunity/netbox
    newName: git.lly.sh/ftsell/lillinfra-netbox

configMapGenerator:
  - name: netbox-env
    envs:
      - config/config.env
  - name: netbox-config
    files:
      - "extra.py=config/extra_config.py"
      - "logging.py=config/logging.py"
      - "plugins.py=config/plugins.py"

secretGenerator:
  - name: netbox-env
    envs:
      - config/config.secret.env
