apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: woodpecker
commonLabels:
  app.kubernetes.io/part-of: woodpecker

resources:
  - manifests/namespace.yml
  - manifests/rbac.yml
  - manifests/server.yml
  - manifests/agent.yml
  - manifests/job-helpers.yml
  - manifests/ingress.yml

images:
  - name: docker.io/woodpeckerci/woodpecker-server
    newTag: "v2.8.2"
  - name: docker.io/woodpeckerci/woodpecker-agent
    newTag: "v2.7.3"

replicas:
  - name: woodpecker-agent
    count: 2

configMapGenerator:
  - name: woodpecker-server
    envs:
      - server.env
  - name: woodpecker-agent
    envs:
      - agent.env

secretGenerator:
  - name: woodpecker-server
    envs:
      - server.secret.env
