apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lb-advertisement
  namespace: metallb-system
spec:
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: lb1
  interfaces:
    - eth0
